### ISSUE TITLE
Image not showing without HeightRequest

### ISSUE THREAD

**Issue by DanMburu** [jonathanpeppers/glidex#34] opened 2019-04-08 09:12 UTC
He is a snippet of my code
```xml
<cardView:CardView.CardViewContent>
                  <StackLayout VerticalOptions="Start"  Margin="0"  Padding="0" HorizontalOptions="Fill">
                    <StackLayout  Padding="5" VerticalOptions="Start" HorizontalOptions="FillAndExpand">
                      <Image Source="{Binding Image}"   HorizontalOptions="FillAndExpand" Aspect="AspectFill" Margin="0" />
                    </StackLayout>
                    <Label  TextColor="#FFFFFF"  VerticalOptions="Start" HorizontalTextAlignment="Center" FontSize = "16" Text="{Binding Name}" />
                  </StackLayout>
                </cardView:CardView.CardViewContent>
              </cardView:CardView>
```

**Comment by jonathanpeppers** [comment] 2019-04-08 13:33
@DanMburu I think this a duplicate of: https://github.com/jonathanpeppers/glidex/issues/10#issuecomment-433109852

Let me know if you have ideas here -- it seems `HeightRequest` / `WidthRequest` are the way to go for now.

**Closed by jonathanpeppers** 2019-04-08 13:33 UTC
